name: clinica_veterinaria
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.8.1 <4.0.0' # Adicionada uma restrição superior por boa prática

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.7.0
  supabase_flutter: ^2.5.0
  google_fonts: ^6.2.1
  sqflite: ^2.4.2
  path_provider: any
  sqflite_common_ffi: any
  shared_preferences: any
  intl: any
  # A linha 'crypto' foi removida daqui pois não é uma dependência declarada

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# A seção flutter e tudo abaixo dela deve estar alinhada à esquerda.
flutter:
  uses-material-design: true


  assets:
    - assets/icons/
    - assets/images/